import type { Candidate } from '../types/candidate';

export const mockCandidates: Candidate[] = [
  {
    id: 'candidate-1',
    name: 'Иванов Иван',
    position: 'react-junior',
    pos_label: 'React — младший программист',
    email: 'ivanov@test.com',
    phone: '+996 555 000 001',
    city: 'Бишкек',
    tg: '@ivanov',
    exp: [['2024-01 — н.в.', 'Test Co', 'Frontend-разработчик', '1 г.']],
    total_exp: '~1 г.',
    stack: 'React, TypeScript, Git',
    edu: 'КГТУ, 2023',
    verdict: 'ПОДХОДИТ',
    vc: 'verdict-green',
    criteria: [
      ['ok', 'React — есть'],
      ['partial', 'TypeScript — базовый'],
    ],
    summary: 'Хороший кандидат с базовым React',
    questions: ['Что такое хук useEffect?'],
    status: 'new',
    createdAt: '2026-06-10T09:00:00Z',
  },
  {
    id: 'candidate-2',
    name: 'Петрова Мария',
    position: 'react-junior',
    pos_label: 'React — младший программист',
    email: 'petrova@test.com',
    phone: '+996 555 000 002',
    city: 'Ош',
    tg: '',
    exp: [],
    total_exp: '0 (студентка)',
    stack: 'HTML, CSS',
    edu: 'КНУ, студентка 2 курс',
    verdict: 'НЕ ПОДХОДИТ',
    vc: 'verdict-red',
    criteria: [['no', 'React — нет']],
    summary: 'Пока не подходит',
    questions: [],
    status: 'reviewing',
    createdAt: '2026-06-09T09:00:00Z',
  },
];
